# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
customer_1 = Customer.create!(first_name: "Lane", last_name: "Bretschneider", email: "lane@example.com", address: "123 Lane St, Lane, CO, 12345")
customer_2 = Customer.create!(first_name: "Taylor", last_name: "Bretschneider", email: "taylor@example.com", address: "123 Taylor St, Taylor, CO, 54321")
customer_3 = Customer.create!(first_name: "Carly", last_name: "Bretschneider", email: "carly@example.com", address: "123 Carly St, Carly, CO, 56789")
subscription_1 = customer_1.subscriptions.create!(title: "All the... Fall Things", price: 100, status: 1, frequency: 1)
subscription_2 = customer_1.subscriptions.create!(title: "BeauTEAful Love", price: 75, status: 2, frequency: 2)
subscription_3 = customer_2.subscriptions.create!(title: "Summer Fruit Basket", price: 80, status: 0, frequency: 0)
subscription_4 = customer_3.subscriptions.create!(title: "Caf-fiends", price: 115, status: 2, frequency: 2)
tea_1 = Tea.create!(title: "Pumpkin Spice", description: "Fall in a mug", temperature: "boiling", brew_time: 4)
tea_2 = Tea.create!(title: "Chai High", description: "It's getting spicy", temperature: "boil + 2 minutes cool", brew_time: 5)
tea_3 = Tea.create!(title: "Cinnamon Apple Pie", description: "Just like grandma used to make it", temperature: "boiling", brew_time: 3)
tea_4 = Tea.create!(title: "Cherry Chocolate", description: "Brings you back to the best first date of your life", temperature: "boil + 4 minutes cool", brew_time: 5)
tea_5 = Tea.create!(title: "Strawberry Rose", description: "Sweet and floral", temperature: "boil + 3 minutes", brew_time: 6)
tea_6 = Tea.create!(title: "Blueberry Acai", description: "All the antioxidants", temperature: "boil + 3 minutes", brew_time: 4)
tea_7 = Tea.create!(title: "Lemon Ginger", description: "Citrus and spice makes everything nice", temperature: "boiling", brew_time: 3)
tea_8 = Tea.create!(title: "Peaches and Dream", description: "Southern comfort all day", temperature: "boiling", brew_time: 5)
tea_9 = Tea.create!(title: "Black and Wild", description: "More caffeine than 4 cups of coffee", temperature: "boiling", brew_time: 8)
tea_10 = Tea.create!(title: "Green Monster", description: "Not your average green tea", temperature: "boiling", brew_time: 6)
SubscriptionTea.create!(subscription_id: subscription_1.id, tea_id: tea_1.id)
SubscriptionTea.create!(subscription_id: subscription_1.id, tea_id: tea_2.id)
SubscriptionTea.create!(subscription_id: subscription_1.id, tea_id: tea_3.id)
SubscriptionTea.create!(subscription_id: subscription_2.id, tea_id: tea_4.id)
SubscriptionTea.create!(subscription_id: subscription_2.id, tea_id: tea_5.id)
SubscriptionTea.create!(subscription_id: subscription_3.id, tea_id: tea_5.id)
SubscriptionTea.create!(subscription_id: subscription_3.id, tea_id: tea_6.id)
SubscriptionTea.create!(subscription_id: subscription_3.id, tea_id: tea_7.id)
SubscriptionTea.create!(subscription_id: subscription_3.id, tea_id: tea_8.id)
SubscriptionTea.create!(subscription_id: subscription_4.id, tea_id: tea_2.id)
SubscriptionTea.create!(subscription_id: subscription_4.id, tea_id: tea_9.id)
SubscriptionTea.create!(subscription_id: subscription_4.id, tea_id: tea_10.id)